import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import { Inter } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "600", "700", "800"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body className={`${inter.className} relative bg-slate-950 min-h-screen text-white overflow-x-hidden`}>

  {/* Background Glow */}
  <div className="fixed inset-0 -z-10">
    <div className="absolute bottom-0 left-[-20%] top-[-10%] h-[500px] w-[500px] rounded-full 
      bg-[radial-gradient(circle_farthest-side,rgba(255,0,182,.15),transparent)]">
    </div>

    <div className="absolute bottom-0 right-[-20%] top-[-10%] h-[500px] w-[500px] rounded-full 
      bg-[radial-gradient(circle_farthest-side,rgba(0,255,255,.15),transparent)]">
    </div>
  </div>

  <Navbar />
  {children}

</body>
    </html>
  );
}
